version: 2

sources:
  - name: raw
    schema: source
    tables:
      - name: weather
        identifier: source_weather
  - name: dim_data
    schema: dim
    tables:
      - name: area
        identifier: dim_area
