version: 1

sources:
  - name: raw_transport
    schema: source

    tables:
      - name: bus
        identifier: source_bus
        loaded_at_field: created_at
      - name: subway
        identifier: source_subway
        loaded_at_field: created_at
