version: 2

sources:
  - name: raw
    schema: source
    tables:
      - name: population
        identifier: source_population
      - name: event
        identifier: source_event

  - name: dim_data
    schema: dim
    tables:
      - name: area
        identifier: dim_area
