name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  code-quality-checks:
    runs-on: ["ubuntu-22.04"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ruff Lint Check
        uses: astral-sh/ruff-action@v3
        with:
          args: check .
      - name: Ruff Format Check
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check .
